# Taken from https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency: preview-${{ github.ref }}
jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    steps:
      - name: ftp-delete-action
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDirectories: pr/${{ github.event.pull_request.number }}/
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install and Build 🔧
        run: |
          npm ci --include=dev
          cp src/configs/config.aws.js src/config.js
          npm run build
          npm run style
      - name: Upload 🏗
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v1
