name: Deploy PR Preview
on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
permissions:
  contents: read
  pages: write
  pull-requests: write
  id-token: write
concurrency: preview-${{ github.ref }}
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install and Build 🔧
        run: |
          npm ci --include=dev
          npm run build
          npm run style
          cp src/configs/config.aws.js src/config.js
      - name: Remove prior FTP preview
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDirectories: pr/${{ github.event.pull_request.number }}/
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: pr/${{ github.event.pull_request.number }}/
          dangerous-clean-slate: true
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            PR Preview:
            * [Map](https://preview.ourmap.us/pr/${{ github.event.pull_request.number }}/)
            * [Shield Test](https://preview.ourmap.us/pr/${{ github.event.pull_request.number }}/shieldtest.html)
            * [style.json](https://preview.ourmap.us/pr/${{ github.event.pull_request.number }}/style.json)
            * [taginfo.json](https://preview.ourmap.us/pr/${{ github.event.pull_request.number }}/taginfo.json)
            * ![Sprites 1x][https://preview.ourmap.us/pr/${{ github.event.pull_request.number }}/sprites/sprite.png]
            * ![Sprites 2x][https://preview.ourmap.us/pr/${{ github.event.pull_request.number }}/sprites/sprite@2x.png]
          comment_tag: pr_preview
